from __future__ import annotations

from motor.motor_asyncio import AsyncIOMotorDatabase

from app.clients.wikipedia import RawPoi
from app.models.poi import Poi

# Synthetic page_id ranges assigned by poi_service for non-Wikipedia sources.
# Negative IDs signal a non-Wikipedia source; the range determines which one.
# These must match the ranges in app/services/poi_service.py.
_WIKIDATA_ID_FLOOR = -(1_000_000_000)  # Wikidata: -(1e9 + Q-number)
_GEONAMES_ID_FLOOR = -(2_000_000_000)  # GeoNames: -(2e9 + geonames_id)
_OVERPASS_NODE_FLOOR = -(3_000_000_000)  # Overpass nodes: -(3e9 + osm_id)
_OVERPASS_WAY_FLOOR = -(4_000_000_000)  # Overpass ways
_OVERPASS_RELATION_FLOOR = -(5_000_000_000)  # Overpass relations


def _source_and_id_from_raw(raw: RawPoi) -> tuple[str, str]:
    """Derive (source, source_id) for a RawPoi based on its page_id.

    Wikipedia POIs have positive page_ids (>= 0).
    Non-Wikipedia POIs are assigned negative synthetic page_ids by poi_service,
    with each source occupying a distinct numeric range:

        [0, +inf)              → Wikipedia  (real page IDs are always positive)
        [-1_999_999_999, -1)   → Wikidata   floor = _WIKIDATA_ID_FLOOR  = -1_000_000_000
        [-2_999_999_999, -2_000_000_000] → GeoNames  floor = _GEONAMES_ID_FLOOR  = -2_000_000_000
        [-3_999_999_999, -3_000_000_000] → OSM nodes floor = _OVERPASS_NODE_FLOOR = -3_000_000_000
        [-4_999_999_999, -4_000_000_000] → OSM ways  floor = _OVERPASS_WAY_FLOOR  = -4_000_000_000
        [-inf, -5_000_000_000]           → OSM rels  floor = _OVERPASS_RELATION_FLOOR

    The if-elif chain below uses > on the *floor* of each range (exclusive lower
    bound).  Because we test from the least-negative floor first
    (Wikidata > GeoNames > Overpass) each branch fires only for IDs in its own range.
    The floor value itself belongs to the lower range (e.g. -2_000_000_000 is
    GeoNames:0, not Wikidata).

    INVARIANT: IDs generated by poi_service._xxx_to_synthetic_id() must never
    overflow into an adjacent range.  The current allocations allow up to ~1B
    entities per source, which is well above any real-world ceiling for all
    enabled sources combined.
    """
    pid = raw.page_id

    if pid >= 0:
        return "wikipedia", f"wikipedia:{pid}"

    # Wikidata: pid in [-1_999_999_999, -1]
    # The Wikidata range is strictly above _GEONAMES_ID_FLOOR (-2_000_000_000).
    # Using > (not >=) so the floor value itself falls into GeoNames, which is
    # the range it was allocated to.
    if pid > _GEONAMES_ID_FLOOR:
        q_number = abs(pid) - 1_000_000_000
        return "wikidata", f"wikidata:{-(1_000_000_000 + q_number)}"

    # GeoNames: pid in [-2_999_999_999, -2_000_000_000]
    if pid > _OVERPASS_NODE_FLOOR:
        geonames_id = abs(pid) - 2_000_000_000
        return "geonames", f"geonames:{geonames_id}"

    # Overpass node: pid in [-3_999_999_999, -3_000_000_000]
    if pid > _OVERPASS_WAY_FLOOR:
        osm_id = abs(pid) - 3_000_000_000
        return "overpass", f"overpass:node:{osm_id}"

    # Overpass way: pid in [-4_999_999_999, -4_000_000_000]
    if pid > _OVERPASS_RELATION_FLOOR:
        osm_id = abs(pid) - 4_000_000_000
        return "overpass", f"overpass:way:{osm_id}"

    # Overpass relation: pid <= -5_000_000_000
    osm_id = abs(pid) - 5_000_000_000
    return "overpass", f"overpass:relation:{osm_id}"


async def save_pois(db: AsyncIOMotorDatabase, pois: list[RawPoi]) -> tuple[int, list[str]]:
    """Upsert each POI by source_id.

    Returns:
        (inserted_count, source_ids) -- inserted_count is the number of
        newly created documents; source_ids is the ordered list of
        source_id strings for every POI in *pois* (inserted or not).
    """
    inserted_count = 0
    source_ids: list[str] = []
    for raw in pois:
        source, source_id = _source_and_id_from_raw(raw)
        poi = Poi(
            name=raw.title,
            location={"type": "Point", "coordinates": [raw.lng, raw.lat]},
            source=source,
            source_id=source_id,
        )
        result = await db.pois.update_one(
            {"source_id": poi.source_id},
            {"$set": poi.to_mongo_dict()},
            upsert=True,
        )
        if result.upserted_id is not None:
            inserted_count += 1
        source_ids.append(poi.source_id)
    return inserted_count, source_ids


async def get_poi(db: AsyncIOMotorDatabase, source_id: str) -> Poi | None:
    doc = await db.pois.find_one({"source_id": source_id})
    if doc is None:
        return None
    doc.pop("_id", None)
    return Poi(**doc)


async def save_poi_images(db: AsyncIOMotorDatabase, source_id: str, image_urls: list[str]) -> None:
    """Update a POI's image_refs after fetching real photos for it.

    image_urls may be an empty list -- that's the honest "no real images
    exist" outcome, not an error, and gets stored as such rather than left
    unset and ambiguous with "never checked."
    """
    await db.pois.update_one({"source_id": source_id}, {"$set": {"image_refs": image_urls}})


async def get_pois_by_source_ids(db: AsyncIOMotorDatabase, source_ids: list[str]) -> list[Poi]:
    """Fetch many POIs in one query -- $in avoids N round trips for N source_ids."""
    cursor = db.pois.find({"source_id": {"$in": source_ids}})
    pois = []
    async for doc in cursor:
        doc.pop("_id", None)
        pois.append(Poi(**doc))
    return pois
